<?php


/**
 * This class adds structure of 'cashcount' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:43
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CashcountMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CashcountMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(CashcountPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(CashcountPeer::TABLE_NAME);
		$tMap->setPhpName('Cashcount');
		$tMap->setClassname('Cashcount');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('DATE', 'Date', 'DATE', true, null);

		$tMap->addColumn('ONETH', 'Oneth', 'VARCHAR', false, 255);

		$tMap->addColumn('FIVEH', 'Fiveh', 'VARCHAR', false, 255);

		$tMap->addColumn('TWOH', 'Twoh', 'VARCHAR', false, 255);

		$tMap->addColumn('ONEH', 'Oneh', 'VARCHAR', false, 255);

		$tMap->addColumn('FIFTY', 'Fifty', 'VARCHAR', false, 255);

		$tMap->addColumn('TWENTY', 'Twenty', 'VARCHAR', false, 255);

		$tMap->addColumn('TEN', 'Ten', 'VARCHAR', false, 255);

		$tMap->addColumn('FIVE', 'Five', 'VARCHAR', false, 255);

		$tMap->addColumn('ONE', 'One', 'VARCHAR', false, 255);

		$tMap->addColumn('FIFTYC', 'Fiftyc', 'VARCHAR', false, 255);

		$tMap->addColumn('TWENTYFIVEC', 'Twentyfivec', 'VARCHAR', false, 255);

		$tMap->addColumn('TENC', 'Tenc', 'VARCHAR', false, 255);

		$tMap->addColumn('FIVEC', 'Fivec', 'VARCHAR', false, 255);

		$tMap->addColumn('AMOUNT', 'Amount', 'VARCHAR', false, 255);

		$tMap->addColumn('TOTAL', 'Total', 'VARCHAR', false, 255);

		$tMap->addColumn('OVER', 'Over', 'VARCHAR', false, 255);

		$tMap->addColumn('SHORT', 'Short', 'VARCHAR', false, 255);

		$tMap->addColumn('TERMINAL', 'Terminal', 'VARCHAR', false, 255);

		$tMap->addColumn('CASHIER', 'Cashier', 'VARCHAR', false, 255);

		$tMap->addColumn('TYPE', 'Type', 'VARCHAR', false, 255);

		$tMap->addColumn('REMARKS', 'Remarks', 'VARCHAR', false, 1255);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // CashcountMapBuilder
