<?php


/**
 * This class adds structure of 'mealcharges' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:40
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MealchargesMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MealchargesMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(MealchargesPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(MealchargesPeer::TABLE_NAME);
		$tMap->setPhpName('Mealcharges');
		$tMap->setClassname('Mealcharges');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('MEAL', 'Meal', 'VARCHAR', false, 255);

		$tMap->addColumn('ITEMSERIAL', 'Itemserial', 'VARCHAR', false, 255);

		$tMap->addColumn('UNIT', 'Unit', 'DECIMAL', false, null);

		$tMap->addColumn('COST', 'Cost', 'DECIMAL', false, null);

		$tMap->addColumn('PRICE', 'Price', 'DECIMAL', false, null);

		$tMap->addColumn('SELECT', 'Select', 'VARCHAR', false, 255);

		$tMap->addColumn('QUANTITY', 'Quantity', 'VARCHAR', false, 255);

		$tMap->addColumn('CUSTOMER', 'Customer', 'VARCHAR', false, 255);

		$tMap->addColumn('TERMINAL', 'Terminal', 'VARCHAR', false, 255);

		$tMap->addColumn('STATUS', 'Status', 'VARCHAR', false, 255);

		$tMap->addColumn('VATIN', 'Vatin', 'DECIMAL', false, null);

		$tMap->addColumn('VATEX', 'Vatex', 'DECIMAL', false, null);

		$tMap->addColumn('DATE', 'Date', 'DATE', false, null);

		$tMap->addColumn('COMMENTS', 'Comments', 'VARCHAR', false, 1000);

		$tMap->addColumn('DISCOUNT', 'Discount', 'VARCHAR', false, 255);

		$tMap->addColumn('DISCOUNT1', 'Discount1', 'VARCHAR', false, 255);

		$tMap->addColumn('RECEIPT', 'Receipt', 'VARCHAR', false, 255);

		$tMap->addColumn('ARECEIPT', 'Areceipt', 'VARCHAR', false, 255);

		$tMap->addColumn('JOBORDER', 'Joborder', 'VARCHAR', false, 255);

		$tMap->addColumn('CASHIER', 'Cashier', 'VARCHAR', false, 255);

		$tMap->addColumn('REP', 'Rep', 'VARCHAR', false, 255);

		$tMap->addColumn('SENIOR', 'Senior', 'VARCHAR', false, 255);

		$tMap->addColumn('LOCATION', 'Location', 'VARCHAR', false, 255);

		$tMap->addColumn('RET', 'Ret', 'VARCHAR', false, 255);

		$tMap->addColumn('ORDERNO', 'Orderno', 'VARCHAR', false, 255);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // MealchargesMapBuilder
