<?php


/**
 * This class adds structure of 'returnitems' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:42
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ReturnitemsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ReturnitemsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ReturnitemsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ReturnitemsPeer::TABLE_NAME);
		$tMap->setPhpName('Returnitems');
		$tMap->setClassname('Returnitems');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('PURCHASEORDER', 'Purchaseorder', 'VARCHAR', false, 255);

		$tMap->addColumn('ITEMS', 'Items', 'VARCHAR', false, 255);

		$tMap->addColumn('QUANTITY', 'Quantity', 'DECIMAL', false, null);

		$tMap->addColumn('UNITPRICE', 'Unitprice', 'DECIMAL', false, null);

		$tMap->addColumn('PRICE', 'Price', 'DECIMAL', false, null);

		$tMap->addColumn('DATE', 'Date', 'DATE', false, null);

		$tMap->addColumn('USER', 'User', 'VARCHAR', false, 255);

		$tMap->addColumn('REMARKS', 'Remarks', 'VARCHAR', false, 255);

		$tMap->addColumn('BRANCH', 'Branch', 'VARCHAR', false, 255);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // ReturnitemsMapBuilder
