<?php


/**
 * This class adds structure of 'vendor' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:41
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class VendorMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.VendorMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(VendorPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(VendorPeer::TABLE_NAME);
		$tMap->setPhpName('Vendor');
		$tMap->setClassname('Vendor');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', false, 255);

		$tMap->addColumn('ADDRESS', 'Address', 'VARCHAR', false, 255);

		$tMap->addColumn('CONTACTNAME', 'Contactname', 'VARCHAR', false, 255);

		$tMap->addColumn('CONTACTPHONE', 'Contactphone', 'VARCHAR', false, 255);

		$tMap->addColumn('FAX', 'Fax', 'VARCHAR', false, 255);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', false, 255);

		$tMap->addColumn('TIN', 'Tin', 'VARCHAR', false, 255);

		$tMap->addColumn('FILE', 'File', 'VARCHAR', false, 255);

		$tMap->addColumn('REMARKS', 'Remarks', 'VARCHAR', false, 255);

		$tMap->addColumn('CHARGE', 'Charge', 'VARCHAR', false, 255);

		$tMap->addColumn('OTHER', 'Other', 'VARCHAR', false, 255);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // VendorMapBuilder
