<?php

/**
 * Base class that represents a row from the 'configuration' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:42
 *
 * @package    lib.model.om
 */
abstract class BaseConfiguration extends BaseObject  implements Persistent {


  const PEER = 'ConfigurationPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ConfigurationPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the branch field.
	 * @var        string
	 */
	protected $branch;

	/**
	 * The value for the content field.
	 * @var        string
	 */
	protected $content;

	/**
	 * The value for the footer field.
	 * @var        string
	 */
	protected $footer;

	/**
	 * The value for the file field.
	 * @var        string
	 */
	protected $file;

	/**
	 * The value for the alliance field.
	 * @var        string
	 */
	protected $alliance;

	/**
	 * The value for the giftcert field.
	 * @var        string
	 */
	protected $giftcert;

	/**
	 * The value for the scdiscount field.
	 * @var        string
	 */
	protected $scdiscount;

	/**
	 * The value for the itemdiscount field.
	 * @var        string
	 */
	protected $itemdiscount;

	/**
	 * The value for the discount field.
	 * @var        string
	 */
	protected $discount;

	/**
	 * The value for the demo field.
	 * @var        string
	 */
	protected $demo;

	/**
	 * The value for the points field.
	 * @var        string
	 */
	protected $points;

	/**
	 * The value for the transdate field.
	 * @var        string
	 */
	protected $transdate;

	/**
	 * The value for the transon field.
	 * @var        string
	 */
	protected $transon;

	/**
	 * The value for the assistant field.
	 * @var        string
	 */
	protected $assistant;

	/**
	 * The value for the weighting field.
	 * @var        string
	 */
	protected $weighting;

	/**
	 * The value for the joborder field.
	 * @var        string
	 */
	protected $joborder;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseConfiguration object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [branch] column value.
	 * 
	 * @return     string
	 */
	public function getBranch()
	{
		return $this->branch;
	}

	/**
	 * Get the [content] column value.
	 * 
	 * @return     string
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Get the [footer] column value.
	 * 
	 * @return     string
	 */
	public function getFooter()
	{
		return $this->footer;
	}

	/**
	 * Get the [file] column value.
	 * 
	 * @return     string
	 */
	public function getFile()
	{
		return $this->file;
	}

	/**
	 * Get the [alliance] column value.
	 * 
	 * @return     string
	 */
	public function getAlliance()
	{
		return $this->alliance;
	}

	/**
	 * Get the [giftcert] column value.
	 * 
	 * @return     string
	 */
	public function getGiftcert()
	{
		return $this->giftcert;
	}

	/**
	 * Get the [scdiscount] column value.
	 * 
	 * @return     string
	 */
	public function getScdiscount()
	{
		return $this->scdiscount;
	}

	/**
	 * Get the [itemdiscount] column value.
	 * 
	 * @return     string
	 */
	public function getItemdiscount()
	{
		return $this->itemdiscount;
	}

	/**
	 * Get the [discount] column value.
	 * 
	 * @return     string
	 */
	public function getDiscount()
	{
		return $this->discount;
	}

	/**
	 * Get the [demo] column value.
	 * 
	 * @return     string
	 */
	public function getDemo()
	{
		return $this->demo;
	}

	/**
	 * Get the [points] column value.
	 * 
	 * @return     string
	 */
	public function getPoints()
	{
		return $this->points;
	}

	/**
	 * Get the [optionally formatted] temporal [transdate] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getTransdate($format = 'Y-m-d')
	{
		if ($this->transdate === null) {
			return null;
		}


		if ($this->transdate === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->transdate);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->transdate, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [transon] column value.
	 * 
	 * @return     string
	 */
	public function getTranson()
	{
		return $this->transon;
	}

	/**
	 * Get the [assistant] column value.
	 * 
	 * @return     string
	 */
	public function getAssistant()
	{
		return $this->assistant;
	}

	/**
	 * Get the [weighting] column value.
	 * 
	 * @return     string
	 */
	public function getWeighting()
	{
		return $this->weighting;
	}

	/**
	 * Get the [joborder] column value.
	 * 
	 * @return     string
	 */
	public function getJoborder()
	{
		return $this->joborder;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ConfigurationPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = ConfigurationPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [branch] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setBranch($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->branch !== $v) {
			$this->branch = $v;
			$this->modifiedColumns[] = ConfigurationPeer::BRANCH;
		}

		return $this;
	} // setBranch()

	/**
	 * Set the value of [content] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setContent($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->content !== $v) {
			$this->content = $v;
			$this->modifiedColumns[] = ConfigurationPeer::CONTENT;
		}

		return $this;
	} // setContent()

	/**
	 * Set the value of [footer] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setFooter($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->footer !== $v) {
			$this->footer = $v;
			$this->modifiedColumns[] = ConfigurationPeer::FOOTER;
		}

		return $this;
	} // setFooter()

	/**
	 * Set the value of [file] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setFile($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->file !== $v) {
			$this->file = $v;
			$this->modifiedColumns[] = ConfigurationPeer::FILE;
		}

		return $this;
	} // setFile()

	/**
	 * Set the value of [alliance] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setAlliance($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->alliance !== $v) {
			$this->alliance = $v;
			$this->modifiedColumns[] = ConfigurationPeer::ALLIANCE;
		}

		return $this;
	} // setAlliance()

	/**
	 * Set the value of [giftcert] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setGiftcert($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->giftcert !== $v) {
			$this->giftcert = $v;
			$this->modifiedColumns[] = ConfigurationPeer::GIFTCERT;
		}

		return $this;
	} // setGiftcert()

	/**
	 * Set the value of [scdiscount] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setScdiscount($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->scdiscount !== $v) {
			$this->scdiscount = $v;
			$this->modifiedColumns[] = ConfigurationPeer::SCDISCOUNT;
		}

		return $this;
	} // setScdiscount()

	/**
	 * Set the value of [itemdiscount] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setItemdiscount($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->itemdiscount !== $v) {
			$this->itemdiscount = $v;
			$this->modifiedColumns[] = ConfigurationPeer::ITEMDISCOUNT;
		}

		return $this;
	} // setItemdiscount()

	/**
	 * Set the value of [discount] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setDiscount($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->discount !== $v) {
			$this->discount = $v;
			$this->modifiedColumns[] = ConfigurationPeer::DISCOUNT;
		}

		return $this;
	} // setDiscount()

	/**
	 * Set the value of [demo] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setDemo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->demo !== $v) {
			$this->demo = $v;
			$this->modifiedColumns[] = ConfigurationPeer::DEMO;
		}

		return $this;
	} // setDemo()

	/**
	 * Set the value of [points] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setPoints($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->points !== $v) {
			$this->points = $v;
			$this->modifiedColumns[] = ConfigurationPeer::POINTS;
		}

		return $this;
	} // setPoints()

	/**
	 * Sets the value of [transdate] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setTransdate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->transdate !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->transdate !== null && $tmpDt = new DateTime($this->transdate)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->transdate = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = ConfigurationPeer::TRANSDATE;
			}
		} // if either are not null

		return $this;
	} // setTransdate()

	/**
	 * Set the value of [transon] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setTranson($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->transon !== $v) {
			$this->transon = $v;
			$this->modifiedColumns[] = ConfigurationPeer::TRANSON;
		}

		return $this;
	} // setTranson()

	/**
	 * Set the value of [assistant] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setAssistant($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->assistant !== $v) {
			$this->assistant = $v;
			$this->modifiedColumns[] = ConfigurationPeer::ASSISTANT;
		}

		return $this;
	} // setAssistant()

	/**
	 * Set the value of [weighting] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setWeighting($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->weighting !== $v) {
			$this->weighting = $v;
			$this->modifiedColumns[] = ConfigurationPeer::WEIGHTING;
		}

		return $this;
	} // setWeighting()

	/**
	 * Set the value of [joborder] column.
	 * 
	 * @param      string $v new value
	 * @return     Configuration The current object (for fluent API support)
	 */
	public function setJoborder($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->joborder !== $v) {
			$this->joborder = $v;
			$this->modifiedColumns[] = ConfigurationPeer::JOBORDER;
		}

		return $this;
	} // setJoborder()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->branch = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->content = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->footer = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->file = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->alliance = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->giftcert = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->scdiscount = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->itemdiscount = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->discount = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->demo = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->points = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->transdate = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->transon = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->assistant = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->weighting = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->joborder = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 18; // 18 = ConfigurationPeer::NUM_COLUMNS - ConfigurationPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Configuration object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ConfigurationPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseConfiguration:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ConfigurationPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseConfiguration:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseConfiguration:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ConfigurationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseConfiguration:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ConfigurationPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ConfigurationPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ConfigurationPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ConfigurationPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ConfigurationPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ConfigurationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getBranch();
				break;
			case 3:
				return $this->getContent();
				break;
			case 4:
				return $this->getFooter();
				break;
			case 5:
				return $this->getFile();
				break;
			case 6:
				return $this->getAlliance();
				break;
			case 7:
				return $this->getGiftcert();
				break;
			case 8:
				return $this->getScdiscount();
				break;
			case 9:
				return $this->getItemdiscount();
				break;
			case 10:
				return $this->getDiscount();
				break;
			case 11:
				return $this->getDemo();
				break;
			case 12:
				return $this->getPoints();
				break;
			case 13:
				return $this->getTransdate();
				break;
			case 14:
				return $this->getTranson();
				break;
			case 15:
				return $this->getAssistant();
				break;
			case 16:
				return $this->getWeighting();
				break;
			case 17:
				return $this->getJoborder();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ConfigurationPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getBranch(),
			$keys[3] => $this->getContent(),
			$keys[4] => $this->getFooter(),
			$keys[5] => $this->getFile(),
			$keys[6] => $this->getAlliance(),
			$keys[7] => $this->getGiftcert(),
			$keys[8] => $this->getScdiscount(),
			$keys[9] => $this->getItemdiscount(),
			$keys[10] => $this->getDiscount(),
			$keys[11] => $this->getDemo(),
			$keys[12] => $this->getPoints(),
			$keys[13] => $this->getTransdate(),
			$keys[14] => $this->getTranson(),
			$keys[15] => $this->getAssistant(),
			$keys[16] => $this->getWeighting(),
			$keys[17] => $this->getJoborder(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ConfigurationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setBranch($value);
				break;
			case 3:
				$this->setContent($value);
				break;
			case 4:
				$this->setFooter($value);
				break;
			case 5:
				$this->setFile($value);
				break;
			case 6:
				$this->setAlliance($value);
				break;
			case 7:
				$this->setGiftcert($value);
				break;
			case 8:
				$this->setScdiscount($value);
				break;
			case 9:
				$this->setItemdiscount($value);
				break;
			case 10:
				$this->setDiscount($value);
				break;
			case 11:
				$this->setDemo($value);
				break;
			case 12:
				$this->setPoints($value);
				break;
			case 13:
				$this->setTransdate($value);
				break;
			case 14:
				$this->setTranson($value);
				break;
			case 15:
				$this->setAssistant($value);
				break;
			case 16:
				$this->setWeighting($value);
				break;
			case 17:
				$this->setJoborder($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ConfigurationPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setBranch($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setContent($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFooter($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFile($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setAlliance($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setGiftcert($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setScdiscount($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setItemdiscount($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDiscount($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setDemo($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setPoints($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setTransdate($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setTranson($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setAssistant($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setWeighting($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setJoborder($arr[$keys[17]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ConfigurationPeer::DATABASE_NAME);

		if ($this->isColumnModified(ConfigurationPeer::ID)) $criteria->add(ConfigurationPeer::ID, $this->id);
		if ($this->isColumnModified(ConfigurationPeer::NAME)) $criteria->add(ConfigurationPeer::NAME, $this->name);
		if ($this->isColumnModified(ConfigurationPeer::BRANCH)) $criteria->add(ConfigurationPeer::BRANCH, $this->branch);
		if ($this->isColumnModified(ConfigurationPeer::CONTENT)) $criteria->add(ConfigurationPeer::CONTENT, $this->content);
		if ($this->isColumnModified(ConfigurationPeer::FOOTER)) $criteria->add(ConfigurationPeer::FOOTER, $this->footer);
		if ($this->isColumnModified(ConfigurationPeer::FILE)) $criteria->add(ConfigurationPeer::FILE, $this->file);
		if ($this->isColumnModified(ConfigurationPeer::ALLIANCE)) $criteria->add(ConfigurationPeer::ALLIANCE, $this->alliance);
		if ($this->isColumnModified(ConfigurationPeer::GIFTCERT)) $criteria->add(ConfigurationPeer::GIFTCERT, $this->giftcert);
		if ($this->isColumnModified(ConfigurationPeer::SCDISCOUNT)) $criteria->add(ConfigurationPeer::SCDISCOUNT, $this->scdiscount);
		if ($this->isColumnModified(ConfigurationPeer::ITEMDISCOUNT)) $criteria->add(ConfigurationPeer::ITEMDISCOUNT, $this->itemdiscount);
		if ($this->isColumnModified(ConfigurationPeer::DISCOUNT)) $criteria->add(ConfigurationPeer::DISCOUNT, $this->discount);
		if ($this->isColumnModified(ConfigurationPeer::DEMO)) $criteria->add(ConfigurationPeer::DEMO, $this->demo);
		if ($this->isColumnModified(ConfigurationPeer::POINTS)) $criteria->add(ConfigurationPeer::POINTS, $this->points);
		if ($this->isColumnModified(ConfigurationPeer::TRANSDATE)) $criteria->add(ConfigurationPeer::TRANSDATE, $this->transdate);
		if ($this->isColumnModified(ConfigurationPeer::TRANSON)) $criteria->add(ConfigurationPeer::TRANSON, $this->transon);
		if ($this->isColumnModified(ConfigurationPeer::ASSISTANT)) $criteria->add(ConfigurationPeer::ASSISTANT, $this->assistant);
		if ($this->isColumnModified(ConfigurationPeer::WEIGHTING)) $criteria->add(ConfigurationPeer::WEIGHTING, $this->weighting);
		if ($this->isColumnModified(ConfigurationPeer::JOBORDER)) $criteria->add(ConfigurationPeer::JOBORDER, $this->joborder);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ConfigurationPeer::DATABASE_NAME);

		$criteria->add(ConfigurationPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Configuration (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setBranch($this->branch);

		$copyObj->setContent($this->content);

		$copyObj->setFooter($this->footer);

		$copyObj->setFile($this->file);

		$copyObj->setAlliance($this->alliance);

		$copyObj->setGiftcert($this->giftcert);

		$copyObj->setScdiscount($this->scdiscount);

		$copyObj->setItemdiscount($this->itemdiscount);

		$copyObj->setDiscount($this->discount);

		$copyObj->setDemo($this->demo);

		$copyObj->setPoints($this->points);

		$copyObj->setTransdate($this->transdate);

		$copyObj->setTranson($this->transon);

		$copyObj->setAssistant($this->assistant);

		$copyObj->setWeighting($this->weighting);

		$copyObj->setJoborder($this->joborder);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Configuration Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ConfigurationPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ConfigurationPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseConfiguration:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseConfiguration::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseConfiguration
