<?php

/**
 * Base static class for performing query and update operations on the 'receipt' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:41
 *
 * @package    lib.model.om
 */
abstract class BaseReceiptPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'receipt';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Receipt';

	/** The total number of columns. */
	const NUM_COLUMNS = 27;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'receipt.ID';

	/** the column name for the ORNUMBER field */
	const ORNUMBER = 'receipt.ORNUMBER';

	/** the column name for the TABLE field */
	const TABLE = 'receipt.TABLE';

	/** the column name for the CASHIER field */
	const CASHIER = 'receipt.CASHIER';

	/** the column name for the REP field */
	const REP = 'receipt.REP';

	/** the column name for the DATE field */
	const DATE = 'receipt.DATE';

	/** the column name for the SUBTOTAL field */
	const SUBTOTAL = 'receipt.SUBTOTAL';

	/** the column name for the VATABLE field */
	const VATABLE = 'receipt.VATABLE';

	/** the column name for the VATIN field */
	const VATIN = 'receipt.VATIN';

	/** the column name for the VATEX field */
	const VATEX = 'receipt.VATEX';

	/** the column name for the SENIOR field */
	const SENIOR = 'receipt.SENIOR';

	/** the column name for the DISCOUNT field */
	const DISCOUNT = 'receipt.DISCOUNT';

	/** the column name for the TOTAL field */
	const TOTAL = 'receipt.TOTAL';

	/** the column name for the STATUS field */
	const STATUS = 'receipt.STATUS';

	/** the column name for the TYPE field */
	const TYPE = 'receipt.TYPE';

	/** the column name for the COMMENTS field */
	const COMMENTS = 'receipt.COMMENTS';

	/** the column name for the CUSTOMER field */
	const CUSTOMER = 'receipt.CUSTOMER';

	/** the column name for the NAME field */
	const NAME = 'receipt.NAME';

	/** the column name for the TIN field */
	const TIN = 'receipt.TIN';

	/** the column name for the ADDRESS field */
	const ADDRESS = 'receipt.ADDRESS';

	/** the column name for the ARORDER field */
	const ARORDER = 'receipt.ARORDER';

	/** the column name for the SMAC field */
	const SMAC = 'receipt.SMAC';

	/** the column name for the EPLUS field */
	const EPLUS = 'receipt.EPLUS';

	/** the column name for the CREDIT field */
	const CREDIT = 'receipt.CREDIT';

	/** the column name for the JOBORDER field */
	const JOBORDER = 'receipt.JOBORDER';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'receipt.UPDATED_AT';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'receipt.CREATED_AT';

	/**
	 * An identiy map to hold any loaded instances of Receipt objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Receipt[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Ornumber', 'Table', 'Cashier', 'Rep', 'Date', 'Subtotal', 'Vatable', 'Vatin', 'Vatex', 'Senior', 'Discount', 'Total', 'Status', 'Type', 'Comments', 'Customer', 'Name', 'Tin', 'Address', 'Arorder', 'Smac', 'Eplus', 'Credit', 'Joborder', 'UpdatedAt', 'CreatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'ornumber', 'table', 'cashier', 'rep', 'date', 'subtotal', 'vatable', 'vatin', 'vatex', 'senior', 'discount', 'total', 'status', 'type', 'comments', 'customer', 'name', 'tin', 'address', 'arorder', 'smac', 'eplus', 'credit', 'joborder', 'updatedAt', 'createdAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::ORNUMBER, self::TABLE, self::CASHIER, self::REP, self::DATE, self::SUBTOTAL, self::VATABLE, self::VATIN, self::VATEX, self::SENIOR, self::DISCOUNT, self::TOTAL, self::STATUS, self::TYPE, self::COMMENTS, self::CUSTOMER, self::NAME, self::TIN, self::ADDRESS, self::ARORDER, self::SMAC, self::EPLUS, self::CREDIT, self::JOBORDER, self::UPDATED_AT, self::CREATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'ornumber', 'table', 'cashier', 'rep', 'date', 'subtotal', 'vatable', 'vatin', 'vatex', 'senior', 'discount', 'total', 'status', 'type', 'comments', 'customer', 'name', 'tin', 'address', 'arorder', 'smac', 'eplus', 'credit', 'joborder', 'updated_at', 'created_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Ornumber' => 1, 'Table' => 2, 'Cashier' => 3, 'Rep' => 4, 'Date' => 5, 'Subtotal' => 6, 'Vatable' => 7, 'Vatin' => 8, 'Vatex' => 9, 'Senior' => 10, 'Discount' => 11, 'Total' => 12, 'Status' => 13, 'Type' => 14, 'Comments' => 15, 'Customer' => 16, 'Name' => 17, 'Tin' => 18, 'Address' => 19, 'Arorder' => 20, 'Smac' => 21, 'Eplus' => 22, 'Credit' => 23, 'Joborder' => 24, 'UpdatedAt' => 25, 'CreatedAt' => 26, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'ornumber' => 1, 'table' => 2, 'cashier' => 3, 'rep' => 4, 'date' => 5, 'subtotal' => 6, 'vatable' => 7, 'vatin' => 8, 'vatex' => 9, 'senior' => 10, 'discount' => 11, 'total' => 12, 'status' => 13, 'type' => 14, 'comments' => 15, 'customer' => 16, 'name' => 17, 'tin' => 18, 'address' => 19, 'arorder' => 20, 'smac' => 21, 'eplus' => 22, 'credit' => 23, 'joborder' => 24, 'updatedAt' => 25, 'createdAt' => 26, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::ORNUMBER => 1, self::TABLE => 2, self::CASHIER => 3, self::REP => 4, self::DATE => 5, self::SUBTOTAL => 6, self::VATABLE => 7, self::VATIN => 8, self::VATEX => 9, self::SENIOR => 10, self::DISCOUNT => 11, self::TOTAL => 12, self::STATUS => 13, self::TYPE => 14, self::COMMENTS => 15, self::CUSTOMER => 16, self::NAME => 17, self::TIN => 18, self::ADDRESS => 19, self::ARORDER => 20, self::SMAC => 21, self::EPLUS => 22, self::CREDIT => 23, self::JOBORDER => 24, self::UPDATED_AT => 25, self::CREATED_AT => 26, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'ornumber' => 1, 'table' => 2, 'cashier' => 3, 'rep' => 4, 'date' => 5, 'subtotal' => 6, 'vatable' => 7, 'vatin' => 8, 'vatex' => 9, 'senior' => 10, 'discount' => 11, 'total' => 12, 'status' => 13, 'type' => 14, 'comments' => 15, 'customer' => 16, 'name' => 17, 'tin' => 18, 'address' => 19, 'arorder' => 20, 'smac' => 21, 'eplus' => 22, 'credit' => 23, 'joborder' => 24, 'updated_at' => 25, 'created_at' => 26, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new ReceiptMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. ReceiptPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(ReceiptPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(ReceiptPeer::ID);

		$criteria->addSelectColumn(ReceiptPeer::ORNUMBER);

		$criteria->addSelectColumn(ReceiptPeer::TABLE);

		$criteria->addSelectColumn(ReceiptPeer::CASHIER);

		$criteria->addSelectColumn(ReceiptPeer::REP);

		$criteria->addSelectColumn(ReceiptPeer::DATE);

		$criteria->addSelectColumn(ReceiptPeer::SUBTOTAL);

		$criteria->addSelectColumn(ReceiptPeer::VATABLE);

		$criteria->addSelectColumn(ReceiptPeer::VATIN);

		$criteria->addSelectColumn(ReceiptPeer::VATEX);

		$criteria->addSelectColumn(ReceiptPeer::SENIOR);

		$criteria->addSelectColumn(ReceiptPeer::DISCOUNT);

		$criteria->addSelectColumn(ReceiptPeer::TOTAL);

		$criteria->addSelectColumn(ReceiptPeer::STATUS);

		$criteria->addSelectColumn(ReceiptPeer::TYPE);

		$criteria->addSelectColumn(ReceiptPeer::COMMENTS);

		$criteria->addSelectColumn(ReceiptPeer::CUSTOMER);

		$criteria->addSelectColumn(ReceiptPeer::NAME);

		$criteria->addSelectColumn(ReceiptPeer::TIN);

		$criteria->addSelectColumn(ReceiptPeer::ADDRESS);

		$criteria->addSelectColumn(ReceiptPeer::ARORDER);

		$criteria->addSelectColumn(ReceiptPeer::SMAC);

		$criteria->addSelectColumn(ReceiptPeer::EPLUS);

		$criteria->addSelectColumn(ReceiptPeer::CREDIT);

		$criteria->addSelectColumn(ReceiptPeer::JOBORDER);

		$criteria->addSelectColumn(ReceiptPeer::UPDATED_AT);

		$criteria->addSelectColumn(ReceiptPeer::CREATED_AT);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ReceiptPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ReceiptPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseReceiptPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseReceiptPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Receipt
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = ReceiptPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return ReceiptPeer::populateObjects(ReceiptPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseReceiptPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseReceiptPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			ReceiptPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Receipt $value A Receipt object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Receipt $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Receipt object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Receipt) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Receipt object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Receipt Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = ReceiptPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = ReceiptPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = ReceiptPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				ReceiptPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return ReceiptPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Receipt or Criteria object.
	 *
	 * @param      mixed $values Criteria or Receipt object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseReceiptPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseReceiptPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Receipt object
		}

		if ($criteria->containsKey(ReceiptPeer::ID) && $criteria->keyContainsValue(ReceiptPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.ReceiptPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseReceiptPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseReceiptPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Receipt or Criteria object.
	 *
	 * @param      mixed $values Criteria or Receipt object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseReceiptPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseReceiptPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(ReceiptPeer::ID);
			$selectCriteria->add(ReceiptPeer::ID, $criteria->remove(ReceiptPeer::ID), $comparison);

		} else { // $values is Receipt object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseReceiptPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseReceiptPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the receipt table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(ReceiptPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Receipt or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Receipt object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			ReceiptPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Receipt) {
			// invalidate the cache for this single object
			ReceiptPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(ReceiptPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				ReceiptPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Receipt object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Receipt $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Receipt $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(ReceiptPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(ReceiptPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(ReceiptPeer::DATABASE_NAME, ReceiptPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = ReceiptPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Receipt
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = ReceiptPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(ReceiptPeer::DATABASE_NAME);
		$criteria->add(ReceiptPeer::ID, $pk);

		$v = ReceiptPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ReceiptPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(ReceiptPeer::DATABASE_NAME);
			$criteria->add(ReceiptPeer::ID, $pks, Criteria::IN);
			$objs = ReceiptPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseReceiptPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the ReceiptPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the ReceiptPeer class:
//
// Propel::getDatabaseMap(ReceiptPeer::DATABASE_NAME)->addTableBuilder(ReceiptPeer::TABLE_NAME, ReceiptPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseReceiptPeer::DATABASE_NAME)->addTableBuilder(BaseReceiptPeer::TABLE_NAME, BaseReceiptPeer::getMapBuilder());

