<?php

/**
 * Base static class for performing query and update operations on the 'mealcharges' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:40
 *
 * @package    lib.model.om
 */
abstract class BaseMealchargesPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'mealcharges';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Mealcharges';

	/** The total number of columns. */
	const NUM_COLUMNS = 28;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'mealcharges.ID';

	/** the column name for the MEAL field */
	const MEAL = 'mealcharges.MEAL';

	/** the column name for the ITEMSERIAL field */
	const ITEMSERIAL = 'mealcharges.ITEMSERIAL';

	/** the column name for the UNIT field */
	const UNIT = 'mealcharges.UNIT';

	/** the column name for the COST field */
	const COST = 'mealcharges.COST';

	/** the column name for the PRICE field */
	const PRICE = 'mealcharges.PRICE';

	/** the column name for the SELECT field */
	const SELECT = 'mealcharges.SELECT';

	/** the column name for the QUANTITY field */
	const QUANTITY = 'mealcharges.QUANTITY';

	/** the column name for the CUSTOMER field */
	const CUSTOMER = 'mealcharges.CUSTOMER';

	/** the column name for the TERMINAL field */
	const TERMINAL = 'mealcharges.TERMINAL';

	/** the column name for the STATUS field */
	const STATUS = 'mealcharges.STATUS';

	/** the column name for the VATIN field */
	const VATIN = 'mealcharges.VATIN';

	/** the column name for the VATEX field */
	const VATEX = 'mealcharges.VATEX';

	/** the column name for the DATE field */
	const DATE = 'mealcharges.DATE';

	/** the column name for the COMMENTS field */
	const COMMENTS = 'mealcharges.COMMENTS';

	/** the column name for the DISCOUNT field */
	const DISCOUNT = 'mealcharges.DISCOUNT';

	/** the column name for the DISCOUNT1 field */
	const DISCOUNT1 = 'mealcharges.DISCOUNT1';

	/** the column name for the RECEIPT field */
	const RECEIPT = 'mealcharges.RECEIPT';

	/** the column name for the ARECEIPT field */
	const ARECEIPT = 'mealcharges.ARECEIPT';

	/** the column name for the JOBORDER field */
	const JOBORDER = 'mealcharges.JOBORDER';

	/** the column name for the CASHIER field */
	const CASHIER = 'mealcharges.CASHIER';

	/** the column name for the REP field */
	const REP = 'mealcharges.REP';

	/** the column name for the SENIOR field */
	const SENIOR = 'mealcharges.SENIOR';

	/** the column name for the LOCATION field */
	const LOCATION = 'mealcharges.LOCATION';

	/** the column name for the RET field */
	const RET = 'mealcharges.RET';

	/** the column name for the ORDERNO field */
	const ORDERNO = 'mealcharges.ORDERNO';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'mealcharges.UPDATED_AT';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'mealcharges.CREATED_AT';

	/**
	 * An identiy map to hold any loaded instances of Mealcharges objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Mealcharges[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Meal', 'Itemserial', 'Unit', 'Cost', 'Price', 'Select', 'Quantity', 'Customer', 'Terminal', 'Status', 'Vatin', 'Vatex', 'Date', 'Comments', 'Discount', 'Discount1', 'Receipt', 'Areceipt', 'Joborder', 'Cashier', 'Rep', 'Senior', 'Location', 'Ret', 'Orderno', 'UpdatedAt', 'CreatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'meal', 'itemserial', 'unit', 'cost', 'price', 'select', 'quantity', 'customer', 'terminal', 'status', 'vatin', 'vatex', 'date', 'comments', 'discount', 'discount1', 'receipt', 'areceipt', 'joborder', 'cashier', 'rep', 'senior', 'location', 'ret', 'orderno', 'updatedAt', 'createdAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::MEAL, self::ITEMSERIAL, self::UNIT, self::COST, self::PRICE, self::SELECT, self::QUANTITY, self::CUSTOMER, self::TERMINAL, self::STATUS, self::VATIN, self::VATEX, self::DATE, self::COMMENTS, self::DISCOUNT, self::DISCOUNT1, self::RECEIPT, self::ARECEIPT, self::JOBORDER, self::CASHIER, self::REP, self::SENIOR, self::LOCATION, self::RET, self::ORDERNO, self::UPDATED_AT, self::CREATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'meal', 'itemserial', 'unit', 'cost', 'price', 'select', 'quantity', 'customer', 'terminal', 'status', 'vatin', 'vatex', 'date', 'comments', 'discount', 'discount1', 'receipt', 'areceipt', 'joborder', 'cashier', 'rep', 'senior', 'location', 'ret', 'orderno', 'updated_at', 'created_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Meal' => 1, 'Itemserial' => 2, 'Unit' => 3, 'Cost' => 4, 'Price' => 5, 'Select' => 6, 'Quantity' => 7, 'Customer' => 8, 'Terminal' => 9, 'Status' => 10, 'Vatin' => 11, 'Vatex' => 12, 'Date' => 13, 'Comments' => 14, 'Discount' => 15, 'Discount1' => 16, 'Receipt' => 17, 'Areceipt' => 18, 'Joborder' => 19, 'Cashier' => 20, 'Rep' => 21, 'Senior' => 22, 'Location' => 23, 'Ret' => 24, 'Orderno' => 25, 'UpdatedAt' => 26, 'CreatedAt' => 27, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'meal' => 1, 'itemserial' => 2, 'unit' => 3, 'cost' => 4, 'price' => 5, 'select' => 6, 'quantity' => 7, 'customer' => 8, 'terminal' => 9, 'status' => 10, 'vatin' => 11, 'vatex' => 12, 'date' => 13, 'comments' => 14, 'discount' => 15, 'discount1' => 16, 'receipt' => 17, 'areceipt' => 18, 'joborder' => 19, 'cashier' => 20, 'rep' => 21, 'senior' => 22, 'location' => 23, 'ret' => 24, 'orderno' => 25, 'updatedAt' => 26, 'createdAt' => 27, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::MEAL => 1, self::ITEMSERIAL => 2, self::UNIT => 3, self::COST => 4, self::PRICE => 5, self::SELECT => 6, self::QUANTITY => 7, self::CUSTOMER => 8, self::TERMINAL => 9, self::STATUS => 10, self::VATIN => 11, self::VATEX => 12, self::DATE => 13, self::COMMENTS => 14, self::DISCOUNT => 15, self::DISCOUNT1 => 16, self::RECEIPT => 17, self::ARECEIPT => 18, self::JOBORDER => 19, self::CASHIER => 20, self::REP => 21, self::SENIOR => 22, self::LOCATION => 23, self::RET => 24, self::ORDERNO => 25, self::UPDATED_AT => 26, self::CREATED_AT => 27, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'meal' => 1, 'itemserial' => 2, 'unit' => 3, 'cost' => 4, 'price' => 5, 'select' => 6, 'quantity' => 7, 'customer' => 8, 'terminal' => 9, 'status' => 10, 'vatin' => 11, 'vatex' => 12, 'date' => 13, 'comments' => 14, 'discount' => 15, 'discount1' => 16, 'receipt' => 17, 'areceipt' => 18, 'joborder' => 19, 'cashier' => 20, 'rep' => 21, 'senior' => 22, 'location' => 23, 'ret' => 24, 'orderno' => 25, 'updated_at' => 26, 'created_at' => 27, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new MealchargesMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. MealchargesPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(MealchargesPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(MealchargesPeer::ID);

		$criteria->addSelectColumn(MealchargesPeer::MEAL);

		$criteria->addSelectColumn(MealchargesPeer::ITEMSERIAL);

		$criteria->addSelectColumn(MealchargesPeer::UNIT);

		$criteria->addSelectColumn(MealchargesPeer::COST);

		$criteria->addSelectColumn(MealchargesPeer::PRICE);

		$criteria->addSelectColumn(MealchargesPeer::SELECT);

		$criteria->addSelectColumn(MealchargesPeer::QUANTITY);

		$criteria->addSelectColumn(MealchargesPeer::CUSTOMER);

		$criteria->addSelectColumn(MealchargesPeer::TERMINAL);

		$criteria->addSelectColumn(MealchargesPeer::STATUS);

		$criteria->addSelectColumn(MealchargesPeer::VATIN);

		$criteria->addSelectColumn(MealchargesPeer::VATEX);

		$criteria->addSelectColumn(MealchargesPeer::DATE);

		$criteria->addSelectColumn(MealchargesPeer::COMMENTS);

		$criteria->addSelectColumn(MealchargesPeer::DISCOUNT);

		$criteria->addSelectColumn(MealchargesPeer::DISCOUNT1);

		$criteria->addSelectColumn(MealchargesPeer::RECEIPT);

		$criteria->addSelectColumn(MealchargesPeer::ARECEIPT);

		$criteria->addSelectColumn(MealchargesPeer::JOBORDER);

		$criteria->addSelectColumn(MealchargesPeer::CASHIER);

		$criteria->addSelectColumn(MealchargesPeer::REP);

		$criteria->addSelectColumn(MealchargesPeer::SENIOR);

		$criteria->addSelectColumn(MealchargesPeer::LOCATION);

		$criteria->addSelectColumn(MealchargesPeer::RET);

		$criteria->addSelectColumn(MealchargesPeer::ORDERNO);

		$criteria->addSelectColumn(MealchargesPeer::UPDATED_AT);

		$criteria->addSelectColumn(MealchargesPeer::CREATED_AT);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(MealchargesPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			MealchargesPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseMealchargesPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseMealchargesPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Mealcharges
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = MealchargesPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return MealchargesPeer::populateObjects(MealchargesPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseMealchargesPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseMealchargesPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			MealchargesPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Mealcharges $value A Mealcharges object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Mealcharges $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Mealcharges object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Mealcharges) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Mealcharges object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Mealcharges Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = MealchargesPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = MealchargesPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = MealchargesPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				MealchargesPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return MealchargesPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Mealcharges or Criteria object.
	 *
	 * @param      mixed $values Criteria or Mealcharges object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseMealchargesPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseMealchargesPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Mealcharges object
		}

		if ($criteria->containsKey(MealchargesPeer::ID) && $criteria->keyContainsValue(MealchargesPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.MealchargesPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseMealchargesPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseMealchargesPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Mealcharges or Criteria object.
	 *
	 * @param      mixed $values Criteria or Mealcharges object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseMealchargesPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseMealchargesPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(MealchargesPeer::ID);
			$selectCriteria->add(MealchargesPeer::ID, $criteria->remove(MealchargesPeer::ID), $comparison);

		} else { // $values is Mealcharges object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseMealchargesPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseMealchargesPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the mealcharges table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(MealchargesPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Mealcharges or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Mealcharges object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			MealchargesPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Mealcharges) {
			// invalidate the cache for this single object
			MealchargesPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(MealchargesPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				MealchargesPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Mealcharges object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Mealcharges $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Mealcharges $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(MealchargesPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(MealchargesPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(MealchargesPeer::DATABASE_NAME, MealchargesPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = MealchargesPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Mealcharges
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = MealchargesPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(MealchargesPeer::DATABASE_NAME);
		$criteria->add(MealchargesPeer::ID, $pk);

		$v = MealchargesPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(MealchargesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(MealchargesPeer::DATABASE_NAME);
			$criteria->add(MealchargesPeer::ID, $pks, Criteria::IN);
			$objs = MealchargesPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseMealchargesPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the MealchargesPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the MealchargesPeer class:
//
// Propel::getDatabaseMap(MealchargesPeer::DATABASE_NAME)->addTableBuilder(MealchargesPeer::TABLE_NAME, MealchargesPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseMealchargesPeer::DATABASE_NAME)->addTableBuilder(BaseMealchargesPeer::TABLE_NAME, BaseMealchargesPeer::getMapBuilder());

