<?php

/**
 * Base class that represents a row from the 'cashcount' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/20 14:41:43
 *
 * @package    lib.model.om
 */
abstract class BaseCashcount extends BaseObject  implements Persistent {


  const PEER = 'CashcountPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CashcountPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * The value for the oneth field.
	 * @var        string
	 */
	protected $oneth;

	/**
	 * The value for the fiveh field.
	 * @var        string
	 */
	protected $fiveh;

	/**
	 * The value for the twoh field.
	 * @var        string
	 */
	protected $twoh;

	/**
	 * The value for the oneh field.
	 * @var        string
	 */
	protected $oneh;

	/**
	 * The value for the fifty field.
	 * @var        string
	 */
	protected $fifty;

	/**
	 * The value for the twenty field.
	 * @var        string
	 */
	protected $twenty;

	/**
	 * The value for the ten field.
	 * @var        string
	 */
	protected $ten;

	/**
	 * The value for the five field.
	 * @var        string
	 */
	protected $five;

	/**
	 * The value for the one field.
	 * @var        string
	 */
	protected $one;

	/**
	 * The value for the fiftyc field.
	 * @var        string
	 */
	protected $fiftyc;

	/**
	 * The value for the twentyfivec field.
	 * @var        string
	 */
	protected $twentyfivec;

	/**
	 * The value for the tenc field.
	 * @var        string
	 */
	protected $tenc;

	/**
	 * The value for the fivec field.
	 * @var        string
	 */
	protected $fivec;

	/**
	 * The value for the amount field.
	 * @var        string
	 */
	protected $amount;

	/**
	 * The value for the total field.
	 * @var        string
	 */
	protected $total;

	/**
	 * The value for the over field.
	 * @var        string
	 */
	protected $over;

	/**
	 * The value for the short field.
	 * @var        string
	 */
	protected $short;

	/**
	 * The value for the terminal field.
	 * @var        string
	 */
	protected $terminal;

	/**
	 * The value for the cashier field.
	 * @var        string
	 */
	protected $cashier;

	/**
	 * The value for the type field.
	 * @var        string
	 */
	protected $type;

	/**
	 * The value for the remarks field.
	 * @var        string
	 */
	protected $remarks;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCashcount object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [oneth] column value.
	 * 
	 * @return     string
	 */
	public function getOneth()
	{
		return $this->oneth;
	}

	/**
	 * Get the [fiveh] column value.
	 * 
	 * @return     string
	 */
	public function getFiveh()
	{
		return $this->fiveh;
	}

	/**
	 * Get the [twoh] column value.
	 * 
	 * @return     string
	 */
	public function getTwoh()
	{
		return $this->twoh;
	}

	/**
	 * Get the [oneh] column value.
	 * 
	 * @return     string
	 */
	public function getOneh()
	{
		return $this->oneh;
	}

	/**
	 * Get the [fifty] column value.
	 * 
	 * @return     string
	 */
	public function getFifty()
	{
		return $this->fifty;
	}

	/**
	 * Get the [twenty] column value.
	 * 
	 * @return     string
	 */
	public function getTwenty()
	{
		return $this->twenty;
	}

	/**
	 * Get the [ten] column value.
	 * 
	 * @return     string
	 */
	public function getTen()
	{
		return $this->ten;
	}

	/**
	 * Get the [five] column value.
	 * 
	 * @return     string
	 */
	public function getFive()
	{
		return $this->five;
	}

	/**
	 * Get the [one] column value.
	 * 
	 * @return     string
	 */
	public function getOne()
	{
		return $this->one;
	}

	/**
	 * Get the [fiftyc] column value.
	 * 
	 * @return     string
	 */
	public function getFiftyc()
	{
		return $this->fiftyc;
	}

	/**
	 * Get the [twentyfivec] column value.
	 * 
	 * @return     string
	 */
	public function getTwentyfivec()
	{
		return $this->twentyfivec;
	}

	/**
	 * Get the [tenc] column value.
	 * 
	 * @return     string
	 */
	public function getTenc()
	{
		return $this->tenc;
	}

	/**
	 * Get the [fivec] column value.
	 * 
	 * @return     string
	 */
	public function getFivec()
	{
		return $this->fivec;
	}

	/**
	 * Get the [amount] column value.
	 * 
	 * @return     string
	 */
	public function getAmount()
	{
		return $this->amount;
	}

	/**
	 * Get the [total] column value.
	 * 
	 * @return     string
	 */
	public function getTotal()
	{
		return $this->total;
	}

	/**
	 * Get the [over] column value.
	 * 
	 * @return     string
	 */
	public function getOver()
	{
		return $this->over;
	}

	/**
	 * Get the [short] column value.
	 * 
	 * @return     string
	 */
	public function getShort()
	{
		return $this->short;
	}

	/**
	 * Get the [terminal] column value.
	 * 
	 * @return     string
	 */
	public function getTerminal()
	{
		return $this->terminal;
	}

	/**
	 * Get the [cashier] column value.
	 * 
	 * @return     string
	 */
	public function getCashier()
	{
		return $this->cashier;
	}

	/**
	 * Get the [type] column value.
	 * 
	 * @return     string
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Get the [remarks] column value.
	 * 
	 * @return     string
	 */
	public function getRemarks()
	{
		return $this->remarks;
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CashcountPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = CashcountPeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Set the value of [oneth] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setOneth($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oneth !== $v) {
			$this->oneth = $v;
			$this->modifiedColumns[] = CashcountPeer::ONETH;
		}

		return $this;
	} // setOneth()

	/**
	 * Set the value of [fiveh] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setFiveh($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fiveh !== $v) {
			$this->fiveh = $v;
			$this->modifiedColumns[] = CashcountPeer::FIVEH;
		}

		return $this;
	} // setFiveh()

	/**
	 * Set the value of [twoh] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setTwoh($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->twoh !== $v) {
			$this->twoh = $v;
			$this->modifiedColumns[] = CashcountPeer::TWOH;
		}

		return $this;
	} // setTwoh()

	/**
	 * Set the value of [oneh] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setOneh($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oneh !== $v) {
			$this->oneh = $v;
			$this->modifiedColumns[] = CashcountPeer::ONEH;
		}

		return $this;
	} // setOneh()

	/**
	 * Set the value of [fifty] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setFifty($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fifty !== $v) {
			$this->fifty = $v;
			$this->modifiedColumns[] = CashcountPeer::FIFTY;
		}

		return $this;
	} // setFifty()

	/**
	 * Set the value of [twenty] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setTwenty($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->twenty !== $v) {
			$this->twenty = $v;
			$this->modifiedColumns[] = CashcountPeer::TWENTY;
		}

		return $this;
	} // setTwenty()

	/**
	 * Set the value of [ten] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setTen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ten !== $v) {
			$this->ten = $v;
			$this->modifiedColumns[] = CashcountPeer::TEN;
		}

		return $this;
	} // setTen()

	/**
	 * Set the value of [five] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setFive($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->five !== $v) {
			$this->five = $v;
			$this->modifiedColumns[] = CashcountPeer::FIVE;
		}

		return $this;
	} // setFive()

	/**
	 * Set the value of [one] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setOne($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->one !== $v) {
			$this->one = $v;
			$this->modifiedColumns[] = CashcountPeer::ONE;
		}

		return $this;
	} // setOne()

	/**
	 * Set the value of [fiftyc] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setFiftyc($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fiftyc !== $v) {
			$this->fiftyc = $v;
			$this->modifiedColumns[] = CashcountPeer::FIFTYC;
		}

		return $this;
	} // setFiftyc()

	/**
	 * Set the value of [twentyfivec] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setTwentyfivec($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->twentyfivec !== $v) {
			$this->twentyfivec = $v;
			$this->modifiedColumns[] = CashcountPeer::TWENTYFIVEC;
		}

		return $this;
	} // setTwentyfivec()

	/**
	 * Set the value of [tenc] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setTenc($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tenc !== $v) {
			$this->tenc = $v;
			$this->modifiedColumns[] = CashcountPeer::TENC;
		}

		return $this;
	} // setTenc()

	/**
	 * Set the value of [fivec] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setFivec($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fivec !== $v) {
			$this->fivec = $v;
			$this->modifiedColumns[] = CashcountPeer::FIVEC;
		}

		return $this;
	} // setFivec()

	/**
	 * Set the value of [amount] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setAmount($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->amount !== $v) {
			$this->amount = $v;
			$this->modifiedColumns[] = CashcountPeer::AMOUNT;
		}

		return $this;
	} // setAmount()

	/**
	 * Set the value of [total] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setTotal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->total !== $v) {
			$this->total = $v;
			$this->modifiedColumns[] = CashcountPeer::TOTAL;
		}

		return $this;
	} // setTotal()

	/**
	 * Set the value of [over] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setOver($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->over !== $v) {
			$this->over = $v;
			$this->modifiedColumns[] = CashcountPeer::OVER;
		}

		return $this;
	} // setOver()

	/**
	 * Set the value of [short] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setShort($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->short !== $v) {
			$this->short = $v;
			$this->modifiedColumns[] = CashcountPeer::SHORT;
		}

		return $this;
	} // setShort()

	/**
	 * Set the value of [terminal] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setTerminal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->terminal !== $v) {
			$this->terminal = $v;
			$this->modifiedColumns[] = CashcountPeer::TERMINAL;
		}

		return $this;
	} // setTerminal()

	/**
	 * Set the value of [cashier] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setCashier($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cashier !== $v) {
			$this->cashier = $v;
			$this->modifiedColumns[] = CashcountPeer::CASHIER;
		}

		return $this;
	} // setCashier()

	/**
	 * Set the value of [type] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->type !== $v) {
			$this->type = $v;
			$this->modifiedColumns[] = CashcountPeer::TYPE;
		}

		return $this;
	} // setType()

	/**
	 * Set the value of [remarks] column.
	 * 
	 * @param      string $v new value
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setRemarks($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->remarks !== $v) {
			$this->remarks = $v;
			$this->modifiedColumns[] = CashcountPeer::REMARKS;
		}

		return $this;
	} // setRemarks()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CashcountPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cashcount The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CashcountPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->date = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->oneth = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->fiveh = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->twoh = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->oneh = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fifty = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->twenty = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->ten = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->five = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->one = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->fiftyc = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->twentyfivec = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->tenc = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->fivec = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->amount = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->total = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->over = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->short = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->terminal = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->cashier = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->type = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->remarks = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->updated_at = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->created_at = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 25; // 25 = CashcountPeer::NUM_COLUMNS - CashcountPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Cashcount object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CashcountPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CashcountPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCashcount:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CashcountPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			CashcountPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCashcount:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCashcount:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isModified() && !$this->isColumnModified(CashcountPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

    if ($this->isNew() && !$this->isColumnModified(CashcountPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CashcountPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCashcount:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			CashcountPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CashcountPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CashcountPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CashcountPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = CashcountPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CashcountPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getDate();
				break;
			case 2:
				return $this->getOneth();
				break;
			case 3:
				return $this->getFiveh();
				break;
			case 4:
				return $this->getTwoh();
				break;
			case 5:
				return $this->getOneh();
				break;
			case 6:
				return $this->getFifty();
				break;
			case 7:
				return $this->getTwenty();
				break;
			case 8:
				return $this->getTen();
				break;
			case 9:
				return $this->getFive();
				break;
			case 10:
				return $this->getOne();
				break;
			case 11:
				return $this->getFiftyc();
				break;
			case 12:
				return $this->getTwentyfivec();
				break;
			case 13:
				return $this->getTenc();
				break;
			case 14:
				return $this->getFivec();
				break;
			case 15:
				return $this->getAmount();
				break;
			case 16:
				return $this->getTotal();
				break;
			case 17:
				return $this->getOver();
				break;
			case 18:
				return $this->getShort();
				break;
			case 19:
				return $this->getTerminal();
				break;
			case 20:
				return $this->getCashier();
				break;
			case 21:
				return $this->getType();
				break;
			case 22:
				return $this->getRemarks();
				break;
			case 23:
				return $this->getUpdatedAt();
				break;
			case 24:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CashcountPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getDate(),
			$keys[2] => $this->getOneth(),
			$keys[3] => $this->getFiveh(),
			$keys[4] => $this->getTwoh(),
			$keys[5] => $this->getOneh(),
			$keys[6] => $this->getFifty(),
			$keys[7] => $this->getTwenty(),
			$keys[8] => $this->getTen(),
			$keys[9] => $this->getFive(),
			$keys[10] => $this->getOne(),
			$keys[11] => $this->getFiftyc(),
			$keys[12] => $this->getTwentyfivec(),
			$keys[13] => $this->getTenc(),
			$keys[14] => $this->getFivec(),
			$keys[15] => $this->getAmount(),
			$keys[16] => $this->getTotal(),
			$keys[17] => $this->getOver(),
			$keys[18] => $this->getShort(),
			$keys[19] => $this->getTerminal(),
			$keys[20] => $this->getCashier(),
			$keys[21] => $this->getType(),
			$keys[22] => $this->getRemarks(),
			$keys[23] => $this->getUpdatedAt(),
			$keys[24] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CashcountPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setDate($value);
				break;
			case 2:
				$this->setOneth($value);
				break;
			case 3:
				$this->setFiveh($value);
				break;
			case 4:
				$this->setTwoh($value);
				break;
			case 5:
				$this->setOneh($value);
				break;
			case 6:
				$this->setFifty($value);
				break;
			case 7:
				$this->setTwenty($value);
				break;
			case 8:
				$this->setTen($value);
				break;
			case 9:
				$this->setFive($value);
				break;
			case 10:
				$this->setOne($value);
				break;
			case 11:
				$this->setFiftyc($value);
				break;
			case 12:
				$this->setTwentyfivec($value);
				break;
			case 13:
				$this->setTenc($value);
				break;
			case 14:
				$this->setFivec($value);
				break;
			case 15:
				$this->setAmount($value);
				break;
			case 16:
				$this->setTotal($value);
				break;
			case 17:
				$this->setOver($value);
				break;
			case 18:
				$this->setShort($value);
				break;
			case 19:
				$this->setTerminal($value);
				break;
			case 20:
				$this->setCashier($value);
				break;
			case 21:
				$this->setType($value);
				break;
			case 22:
				$this->setRemarks($value);
				break;
			case 23:
				$this->setUpdatedAt($value);
				break;
			case 24:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CashcountPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDate($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setOneth($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFiveh($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTwoh($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setOneh($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFifty($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setTwenty($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTen($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFive($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setOne($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setFiftyc($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setTwentyfivec($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setTenc($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setFivec($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setAmount($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setTotal($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setOver($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setShort($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setTerminal($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setCashier($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setType($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setRemarks($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setUpdatedAt($arr[$keys[23]]);
		if (array_key_exists($keys[24], $arr)) $this->setCreatedAt($arr[$keys[24]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CashcountPeer::DATABASE_NAME);

		if ($this->isColumnModified(CashcountPeer::ID)) $criteria->add(CashcountPeer::ID, $this->id);
		if ($this->isColumnModified(CashcountPeer::DATE)) $criteria->add(CashcountPeer::DATE, $this->date);
		if ($this->isColumnModified(CashcountPeer::ONETH)) $criteria->add(CashcountPeer::ONETH, $this->oneth);
		if ($this->isColumnModified(CashcountPeer::FIVEH)) $criteria->add(CashcountPeer::FIVEH, $this->fiveh);
		if ($this->isColumnModified(CashcountPeer::TWOH)) $criteria->add(CashcountPeer::TWOH, $this->twoh);
		if ($this->isColumnModified(CashcountPeer::ONEH)) $criteria->add(CashcountPeer::ONEH, $this->oneh);
		if ($this->isColumnModified(CashcountPeer::FIFTY)) $criteria->add(CashcountPeer::FIFTY, $this->fifty);
		if ($this->isColumnModified(CashcountPeer::TWENTY)) $criteria->add(CashcountPeer::TWENTY, $this->twenty);
		if ($this->isColumnModified(CashcountPeer::TEN)) $criteria->add(CashcountPeer::TEN, $this->ten);
		if ($this->isColumnModified(CashcountPeer::FIVE)) $criteria->add(CashcountPeer::FIVE, $this->five);
		if ($this->isColumnModified(CashcountPeer::ONE)) $criteria->add(CashcountPeer::ONE, $this->one);
		if ($this->isColumnModified(CashcountPeer::FIFTYC)) $criteria->add(CashcountPeer::FIFTYC, $this->fiftyc);
		if ($this->isColumnModified(CashcountPeer::TWENTYFIVEC)) $criteria->add(CashcountPeer::TWENTYFIVEC, $this->twentyfivec);
		if ($this->isColumnModified(CashcountPeer::TENC)) $criteria->add(CashcountPeer::TENC, $this->tenc);
		if ($this->isColumnModified(CashcountPeer::FIVEC)) $criteria->add(CashcountPeer::FIVEC, $this->fivec);
		if ($this->isColumnModified(CashcountPeer::AMOUNT)) $criteria->add(CashcountPeer::AMOUNT, $this->amount);
		if ($this->isColumnModified(CashcountPeer::TOTAL)) $criteria->add(CashcountPeer::TOTAL, $this->total);
		if ($this->isColumnModified(CashcountPeer::OVER)) $criteria->add(CashcountPeer::OVER, $this->over);
		if ($this->isColumnModified(CashcountPeer::SHORT)) $criteria->add(CashcountPeer::SHORT, $this->short);
		if ($this->isColumnModified(CashcountPeer::TERMINAL)) $criteria->add(CashcountPeer::TERMINAL, $this->terminal);
		if ($this->isColumnModified(CashcountPeer::CASHIER)) $criteria->add(CashcountPeer::CASHIER, $this->cashier);
		if ($this->isColumnModified(CashcountPeer::TYPE)) $criteria->add(CashcountPeer::TYPE, $this->type);
		if ($this->isColumnModified(CashcountPeer::REMARKS)) $criteria->add(CashcountPeer::REMARKS, $this->remarks);
		if ($this->isColumnModified(CashcountPeer::UPDATED_AT)) $criteria->add(CashcountPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(CashcountPeer::CREATED_AT)) $criteria->add(CashcountPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CashcountPeer::DATABASE_NAME);

		$criteria->add(CashcountPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Cashcount (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDate($this->date);

		$copyObj->setOneth($this->oneth);

		$copyObj->setFiveh($this->fiveh);

		$copyObj->setTwoh($this->twoh);

		$copyObj->setOneh($this->oneh);

		$copyObj->setFifty($this->fifty);

		$copyObj->setTwenty($this->twenty);

		$copyObj->setTen($this->ten);

		$copyObj->setFive($this->five);

		$copyObj->setOne($this->one);

		$copyObj->setFiftyc($this->fiftyc);

		$copyObj->setTwentyfivec($this->twentyfivec);

		$copyObj->setTenc($this->tenc);

		$copyObj->setFivec($this->fivec);

		$copyObj->setAmount($this->amount);

		$copyObj->setTotal($this->total);

		$copyObj->setOver($this->over);

		$copyObj->setShort($this->short);

		$copyObj->setTerminal($this->terminal);

		$copyObj->setCashier($this->cashier);

		$copyObj->setType($this->type);

		$copyObj->setRemarks($this->remarks);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setCreatedAt($this->created_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Cashcount Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CashcountPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CashcountPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCashcount:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCashcount::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCashcount
