<?php
// auto-generated by sfRoutingConfigHandler
// date: 2021/04/07 06:02:42
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'home',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'vendor_index' => new sfRoute('/vendor/list', array (
  'module' => 'vendor',
  'action' => 'index',
), array (
), array (
)),
'mealcategory' => new sfRoute('/category', array (
  'module' => 'mealcategory',
  'action' => 'index',
), array (
), array (
)),
'display' => new sfRoute('/display', array (
  'module' => 'display',
  'action' => 'index',
), array (
), array (
)),
'sales_order' => new sfRoute('/sales/retail', array (
  'module' => 'sales',
  'action' => 'order',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
'sf_guard_signin' => new sfRoute('/signin', array (
  'module' => 'sfGuardAuth',
  'action' => 'signin',
), array (
), array (
)),
'sf_guard_signout' => new sfRoute('/signout', array (
  'module' => 'sfGuardAuth',
  'action' => 'signout',
), array (
), array (
)),
);
