<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/04/07 06:02:39

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=distribution;host=localhost',
  'username' => 'root',
  'password' => 'kintoz2016',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
