default:
  http_metas:
    content-type: text/html

  metas:
    title:        Kintoz POS
    description:  www.posphilippines.com
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
